var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   o                            ",
   "                                                xxxxyyy!!                       ",
   "   @                                           xxxxxyyy!!xxxx               xx  ",
   "  xx                                          xxxxxxyyy!!xxxx                x  ",
   "  x                            o            xxxxxxxxyyy!!xxxx                x  ",
   "  x                o$        yyyyy      xxxxxxxxxxxxyyy!!xxxx              oox  ",
   "  x      yyyy!!!!yyyyy!!!!xxxxxxxxxx!!!!xxxxxxxxxxxxyyy!!xxxxxxxxyyyyxxxxxxxxx  ",
   "  x      yyyy!!!!yyyyy!!!!xxxxxxxxxx!!!!xxxxxxxxxxxxyyy!!xxxxxxxxyyyyxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],

   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "   @                                                                            ",
    "  xx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  x                    yyyyyyyyyyyyyyyyyyyyyyyyyyy    |                      x  ",
    "  x                    yyyyyyyyyyyyyyyyyyyyyyyyyyy            o              x  ",
    "  x            yyyyyy  !!!yyyyyyyyyyyyyyyyyyyyyyyy          yyyy             x  ",
    "  x          $oyy!!!!  !!!yyyyyyyyyyyyyyyyyyyyyyyy          yyyy             x  ",
    "  x          yyyy!!!!                                       yyyy           $ox  ",
    "  x         yyyyy!!!!                    o                yyyyyy          yyyx  ",
    "  x         yyyyy!!!!          yyy      yyy               yyyyyyyy        yyyx  ",
    "  x         yyyyy!!!!    o$    yyy      yyy               yyyyyyyy         yyx  ",
    "  x         yyyyy!!!!  yyyyy!yyyyyyyy!yyyyyyyy!yyy!!!!  $oyyyyyyyyyyy     !!!x  ",
    "  x     !!yyyyyyy!!!!  yyyyyyyyyyyyyyyyyyyyyyyyyyy!!!!!yyyyyyyyyyyyyyyyyyyyyyx  ",
    "  x     yyyyyyyyy!!!!  yyyyyyyyyyyyyyyyyyyyyyyyyyy!!!!!yyyyyyyyyyyyyyyyyyyyyyx  ",
    "  x o yyyyyyyyyyy!!!!  yyyyyyyyyyyyyyyyyyyyyyyyyyy!!!!!yyyyyyyyyyyyyyyyyyyyyyx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                ",
    "                                                                                "],

    ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
     "     |||         ||         ||                                                  ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "                                                                                ",
     "   @                                                                            ",
     "  xx        o$   ||  o$     ||   o     ||    0    ||    o    ||       o     xx  ",
     "  x!!!!!!yyyyyyy!!!!yyyyyyy!!!!yyyyyyy!!!!yyyyyyy!!!!yyyyyyy!!!!yyyyyyyyyyyyyx  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  x!!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!yyyyy!!!!!!!!!!!!!!!!!!x  ",
     "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
     "                                                                                ",
     "                                                                                "],

     ["                                                                                ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x         yy  yy  yyyyyy  yy  yy     yy      yy  yy  yy    yy                x ",
      " x         yy  yy  yy  yy  yy  yy     yy      yy  yy  yyy   yy                x ",
      " x         yyyyyy  yy  yy  yy  yy     yy  yy  yy  yy  yy y  yy                x ",
      " x           yy    yy  yy  yy  yy     yy  yy  yy  yy  yy  y yy                x ",
      " x           yy    yy  yy  yy  yy     yy  yy  yy  yy  yy   yyy                x ",
      " x           yy    yyyyyy  yyyyyy     yyyyyyyyyy  yy  yy    yy                x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                      @                                     x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x                                                                            x ",
      " x o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o  x ",
      " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
      "                                                                                "],
];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
